# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    allow:
      # Allow only direct updates for
      # Django and any packages starting "django"
      - dependency-name: "ansible*"
        dependency-type: "direct"
      # Allow only production updates for Sphinx
      - dependency-name: "molecule*"
        dependency-type: "direct"
      - dependency-name: "yamllint"
        dependency-type: "direct"
    assignees:
      - "ssbarnea"
    labels:
      - "major"  # reviewer is expected to remove one of them
      - "dependencies"
